<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contenu_Selecteur</name>
   <tag></tag>
   <elementGuidId>b079db1e-efb3-4b1a-848b-bb82b65c86e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wizard-page&quot;]/div[2]/div/div/div[2]/div/div/div[2]/div/rapp-search-input/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;wizard-page&quot;)/div[@class=&quot;inner-content-body&quot;]/div[@class=&quot;container full-height ng-scope&quot;]/div[@class=&quot;container  full-height ng-scope&quot;]/div[@class=&quot;col-sm-4 full-height ng-scope&quot;]/div[@class=&quot;kiezer  ng-scope&quot;]/div[@class=&quot;panel panel-default panel-transparent panel-no-bottom-border&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;search-container&quot;]/rapp-search-input[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control ng-valid ng-valid-maxlength ng-dirty ng-valid-parse ng-touched&quot;][count(. | //input[@type = 'text']) = count(//input[@type = 'text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-valid ng-valid-maxlength ng-dirty ng-valid-parse ng-touched</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>searchQuery</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ debounce: 300 }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-page&quot;)/div[@class=&quot;inner-content-body&quot;]/div[@class=&quot;container full-height ng-scope&quot;]/div[@class=&quot;container  full-height ng-scope&quot;]/div[@class=&quot;col-sm-4 full-height ng-scope&quot;]/div[@class=&quot;kiezer  ng-scope&quot;]/div[@class=&quot;panel panel-default panel-transparent panel-no-bottom-border&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;search-container&quot;]/rapp-search-input[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control ng-valid ng-valid-maxlength ng-dirty ng-valid-parse ng-touched&quot;]</value>
   </webElementProperties>
</WebElementEntity>
