<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Generalites - input name</name>
   <tag></tag>
   <elementGuidId>27bfbe76-f874-4c82-97e3-918c7f7869a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wizard-page&quot;]/div[2]/div/div/div/form/div[1]/div/div/div[2]/div[1]/div/div/div/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wizard-page&quot;]/div[2]/div/div/div/form/div[1]/div/div/div[2]/div[1]/div/div/div/div[1]/div/div/input[count(. | //input[@type = 'text' and @class = 'form-control ng-pristine ng-untouched ng-scope ng-invalid ng-invalid-required ng-valid-maxlength' and @name = 'oms2FR' and @ng-model = 'lang.tekst' and @maxlength = '80' and @ng-if = '!vm.isTextarea' and @ng-blur = '!vm.showAll &amp;&amp; vm.copyTalen()' and @ng-required = 'vm.shouldBeRequired &amp;&amp; (lang.taal === $parent.vm.userLanguageCode)']) = count(//input[@type = 'text' and @class = 'form-control ng-pristine ng-untouched ng-scope ng-invalid ng-invalid-required ng-valid-maxlength' and @name = 'oms2FR' and @ng-model = 'lang.tekst' and @maxlength = '80' and @ng-if = '!vm.isTextarea' and @ng-blur = '!vm.showAll &amp;&amp; vm.copyTalen()' and @ng-required = 'vm.shouldBeRequired &amp;&amp; (lang.taal === $parent.vm.userLanguageCode)'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-scope ng-invalid ng-invalid-required ng-valid-maxlength</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oms2FR</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>lang.tekst</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!vm.isTextarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>!vm.showAll &amp;&amp; vm.copyTalen()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>vm.shouldBeRequired &amp;&amp; (lang.taal === $parent.vm.userLanguageCode)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wizard-page&quot;]/div[2]/div/div/div/form/div[1]/div/div/div[2]/div[1]/div/div/div/div[1]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
