<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_Arrow</name>
   <tag></tag>
   <elementGuidId>c23a72c1-e349-414e-bfa2-fff16073fa12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wizard-page&quot;]/div[1]/div[4]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;wizard-page&quot;)/div[@class=&quot;page-header text-center&quot;]/div[@class=&quot;rapp-wizard-nav ng-scope&quot;]/button[@class=&quot;btn btn-link ng-scope&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isProcessing</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rapp-wizard-navigation-disabled-is-processing</name>
      <type>Main</type>
      <value>isProcessing</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>navvm.gaNaarStap1()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-page&quot;)/div[@class=&quot;page-header text-center&quot;]/div[@class=&quot;rapp-wizard-nav ng-scope&quot;]/button[@class=&quot;btn btn-link ng-scope&quot;]</value>
   </webElementProperties>
</WebElementEntity>
