<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input field for travailleur</name>
   <tag></tag>
   <elementGuidId>939df73e-8610-4dd1-8425-522c3e6c99e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='select2-container select2-container-multi ng-pristine ng-untouched ng-valid ng-scope']//ul[@class='select2-choices']//li[@class='select2-search-field']//input[@class='select2-input'][count(. | //*[contains(@id, 's2id_autogen') and @class = 'select2-input' and @type = 'text' and @autocomplete = 'off' and @autocorrect = 'off' and @autocapitalize = 'off']) = count(//*[contains(@id, 's2id_autogen') and @class = 'select2-input' and @type = 'text' and @autocomplete = 'off' and @autocorrect = 'off' and @autocapitalize = 'off'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s2id_autogen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='select2-container select2-container-multi ng-pristine ng-untouched ng-valid ng-scope']//ul[@class='select2-choices']//li[@class='select2-search-field']//input[@class='select2-input']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
</WebElementEntity>
