<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>info_Icon</name>
   <tag></tag>
   <elementGuidId>c8daa000-51f3-4bfc-8062-75507175eb16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;inner-content my-reports-page ng-scope&quot;]/div[@class=&quot;inner-content-header&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-md-7&quot;]/form[@class=&quot;navbar-form ng-pristine ng-valid ng-valid-maxlength&quot;]/div[@class=&quot;input-group&quot;]/a[@class=&quot;btn btn-default active&quot;][count(. | //a[@class = 'btn btn-default active' and @ng-click = 'vm.toggleShowInfo()' and @ng-class = concat('{' , &quot;'&quot; , 'active' , &quot;'&quot; , ':vm.showInfo}')]) = count(//a[@class = 'btn btn-default active' and @ng-click = 'vm.toggleShowInfo()' and @ng-class = concat('{' , &quot;'&quot; , 'active' , &quot;'&quot; , ':vm.showInfo}')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/ui-view/div/div[1]/nav/div/div[1]/form/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.toggleShowInfo()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active':vm.showInfo}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Afficher rapport descriptions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;inner-content my-reports-page ng-scope&quot;]/div[@class=&quot;inner-content-header&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-md-7&quot;]/form[@class=&quot;navbar-form ng-pristine ng-valid ng-valid-maxlength&quot;]/div[@class=&quot;input-group&quot;]/a[@class=&quot;btn btn-default active&quot;]</value>
   </webElementProperties>
</WebElementEntity>
