<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Definition</name>
   <tag></tag>
   <elementGuidId>16b77141-6eca-4bc0-ac50-f346fca10f4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Definitie')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(text(), 'Definitie')][count(. | //a[@class = 'btn btn-default ng-scope ng-isolate-scope' and @rapp-definitie-link-route = 'definitie' and @rapp-definitie-link = '28063']) = count(//a[@class = 'btn btn-default ng-scope ng-isolate-scope' and @rapp-definitie-link-route = 'definitie' and @rapp-definitie-link = '28063'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default ng-scope ng-isolate-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Definitie
                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(text(), 'Definitie')]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!pagevm.rapport.isHardcodedReport</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rapp-definitie-link-route</name>
      <type>Main</type>
      <value>definitie</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rapp-definitie-link</name>
      <type>Main</type>
      <value>28063</value>
   </webElementProperties>
</WebElementEntity>
