<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioButton_Baser sur un rapport de la Bibliothque</name>
   <tag></tag>
   <elementGuidId>5be33d01-801d-44e2-bcb3-c1025db6686a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typeRapport</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>GebaseerdOpStandaard</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>startvm.typeRapport</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-dirty ng-valid-parse ng-touched</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-page&quot;)/div[@class=&quot;inner-content-body&quot;]/div[@class=&quot;container full-height ng-scope&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;panel panel-default panel-transparent panel-no-bottom-border&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal ng-dirty ng-valid-parse ng-invalid ng-valid-required&quot;]/div[@class=&quot;form-group row ng-scope&quot;]/div[@class=&quot;radio&quot;]/label[1]/input[@class=&quot;ng-valid ng-dirty ng-valid-parse ng-touched&quot;]</value>
   </webElementProperties>
</WebElementEntity>
