<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Brutoloon</description>
   <name>Brutoloon</name>
   <tag></tag>
   <elementGuidId>aafea4d3-1971-4624-acc4-e065495746b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='ng-scope']//span[@text='Brutoloon']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
