<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Montants</name>
   <tag></tag>
   <elementGuidId>73cfa555-1913-4731-93d0-c915ca388d35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/ui-view/ui-view/ui-view/div/div[1]/nav/div/div[2]/div/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content&quot;]/ui-view[@class=&quot;ng-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;inner-content beheer-telwerken ng-scope&quot;]/div[@class=&quot;inner-content-header&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;navbar-right col-lg-6&quot;]/div[@class=&quot;btn-group  pull-right rapp-security-requires-create navbar-btn open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[1][count(. | //a[@ng-click = 'telwerkenvm.createTelwerk(1)']) = count(//a[@ng-click = 'telwerkenvm.createTelwerk(1)'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>telwerkenvm.createTelwerk(1)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Montants</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content&quot;]/ui-view[@class=&quot;ng-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;inner-content beheer-telwerken ng-scope&quot;]/div[@class=&quot;inner-content-header&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;navbar-right col-lg-6&quot;]/div[@class=&quot;btn-group  pull-right rapp-security-requires-create navbar-btn open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
