<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ajouter button</name>
   <tag></tag>
   <elementGuidId>c9b1a1a8-3a05-43b9-979f-819dc64be1a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;rapp-disable-toevoegen-knoppen-tabel&quot;]/table/tfoot/tr/td/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;rapp-disable-toevoegen-knoppen-tabel&quot;]/table/tfoot/tr/td/div/button</value>
   </webElementProperties>
</WebElementEntity>
