<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Label</name>
   <tag></tag>
   <elementGuidId>b32597cc-b469-4f37-9a23-bce74f9198cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/ui-view/ui-view/ui-view/div/div/form/div/div/div[1]/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/ui-view/ui-view/ui-view/div/div/form/div/div/div[1]/div/div/h3</value>
   </webElementProperties>
</WebElementEntity>
