<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dfinition</name>
   <tag></tag>
   <elementGuidId>a0c77b45-e199-4817-a767-664556382dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;inner-content ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/nav[@class=&quot;navbar navbar-default content-nav content-header ng-scope&quot;]/div[@class=&quot;collapse navbar-collapse&quot;]/ul[@class=&quot;nav navbar-nav navbar-left&quot;]/li[4]/div[@class=&quot;btn-group&quot;]/a[@class=&quot;btn btn-default ng-isolate-scope&quot;][count(. | //a[@class = 'btn btn-default ng-isolate-scope' and @rapp-definitie-link = '26077' and @rapp-definitie-link-route = 'definitie' and @rapp-definitie-link-niveau = '2' and @rapp-definitie-link-copy = '0' and @rapp-definitie-link-uitvoering-visualisatie = '1' and @ng-disabled = 'pagevm.processing' and (text() = '
                        Définition
                    ' or . = '
                        Définition
                    ')]) = count(//a[@class = 'btn btn-default ng-isolate-scope' and @rapp-definitie-link = '26077' and @rapp-definitie-link-route = 'definitie' and @rapp-definitie-link-niveau = '2' and @rapp-definitie-link-copy = '0' and @rapp-definitie-link-uitvoering-visualisatie = '1' and @ng-disabled = 'pagevm.processing' and (text() = '
                        Définition
                    ' or . = '
                        Définition
                    ')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>/html/body/div[1]/div[2]/ui-view/div/div[1]/nav/div/ul[1]/li[4]/div/a[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/ui-view/div/div[1]/nav/div/ul/li[4]/div/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default ng-isolate-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rapp-definitie-link</name>
      <type>Main</type>
      <value>26077</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rapp-definitie-link-route</name>
      <type>Main</type>
      <value>definitie</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rapp-definitie-link-niveau</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rapp-definitie-link-copy</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rapp-definitie-link-uitvoering-visualisatie</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>pagevm.processing</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Définition
                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;inner-content ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/nav[@class=&quot;navbar navbar-default content-nav content-header ng-scope&quot;]/div[@class=&quot;collapse navbar-collapse&quot;]/ul[@class=&quot;nav navbar-nav navbar-left&quot;]/li[4]/div[@class=&quot;btn-group&quot;]/a[@class=&quot;btn btn-default ng-isolate-scope&quot;]</value>
   </webElementProperties>
</WebElementEntity>
