<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sauvegarder</name>
   <tag></tag>
   <elementGuidId>f78ef1ad-ea7d-41ab-aae4-8fea8c97605b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wizard-page&quot;]/nav/div/ul[2]/li/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wizard-page&quot;]/nav/div/ul[2]/li/div/button[count(. | //button[@class = 'btn btn-primary navbar-btn rapp-complete-wizard-button ng-scope' and @ng-click = 'navvm.saveOpEindeWizard(opslaanButtonVm.rapport)']) = count(//button[@class = 'btn btn-primary navbar-btn rapp-complete-wizard-button ng-scope' and @ng-click = 'navvm.saveOpEindeWizard(opslaanButtonVm.rapport)'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary navbar-btn rapp-complete-wizard-button ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>navvm.saveOpEindeWizard(opslaanButtonVm.rapport)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sauvegarder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wizard-page&quot;]/nav/div/ul[2]/li/div/button</value>
   </webElementProperties>
</WebElementEntity>
