<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Sexe</name>
   <tag></tag>
   <elementGuidId>867b7f83-e602-4e54-8f83-703150378efc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-transparent ng-scope ng-isolate-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>item.isActive</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sexe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>search</name>
      <type>Main</type>
      <value>kiezervm.queryKiezer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>kiezervm.chooseItem(item)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-page&quot;)/div[@class=&quot;inner-content-body&quot;]/div[@class=&quot;container full-height ng-scope&quot;]/div[@class=&quot;container  full-height ng-scope&quot;]/div[@class=&quot;col-sm-4 full-height ng-scope&quot;]/div[@class=&quot;kiezer  ng-scope&quot;]/div[@class=&quot;panel panel-default panel-transparent panel-no-bottom-border&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;search-container&quot;]/div[@class=&quot;overflow&quot;]/ul[@class=&quot;ng-scope&quot;]/li[@class=&quot;table-group-title ng-scope&quot;]/ul[@class=&quot;ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/li[@class=&quot;table-group-title ng-scope&quot;]/ul[@class=&quot;ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/li[@class=&quot;table-group-title ng-scope&quot;]/ul[@class=&quot;ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/span[@class=&quot;btn btn-sm btn-transparent ng-scope ng-isolate-scope&quot;]</value>
   </webElementProperties>
</WebElementEntity>
